inherit: 
    - models/five.yaml
    - wandb.yaml

model:
    n_dims: 5
    n_positions: 501
    type: stackxy

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    resume_id: stackxy_model_2
    curriculum:
        dims:
            start: 5
            end: 5
            inc: 1
            interval: 2000
