inherit: 
    - models/five.yaml
    - wandb.yaml

model:
    n_dims: 30
    n_positions: 1001

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 30
            inc: 1
            interval: 2000
