inherit: 
    - models/one-four.yaml
    - wandb.yaml

model:
    n_dims: 5
    n_positions: 2001
    type: stackxy
    layer_norm: no_attn_out
    weight_tying: False
    causal_type: prev

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 1500001
    resume_id: stackxy_model_one-four_noise5d_nolyaernormandattnnorm_3
    curriculum:
        dims:
            start: 15
            end: 15
            inc: 1
            interval: 2000
