inherit: 
    - models/one-four.yaml
    - wandb.yaml

model:
    n_dims: 15
    n_positions: 2001
    type: stackxy
    layer_norm: no_attn_out

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 1000001
    resume_id: stackxy_model_one-four_noise15d_nolyaernormandattnnorm_dtrain_1
    curriculum:
        dims:
            start: 5
            end: 15
            inc: 1
            interval: 2000
